### ISSUE TITLE
Remove text "Run Program:"

### ISSUE THREAD

**Issue by GreenLunar** [WdesktopX/gmrun#14]
Honestly, do gmrum users really need it?

**Comment by wdlkmpx** [comment]
That sounds like a good idea since the app is not internationalized

What's do you think @mazes-80  ?

**Comment by mazes-80** [comment]
Feel free to remove it.
I switched to awesome wm, still use gmrun alongside with an awesome equivalent parsing only desktop files. They use only "Run:", I feel it make thing more concise.

**Comment by wdlkmpx** [comment]
Do you also want to remove the label widget that contains the text? 'Cause that's not possible

gmrun supports a bash-like search, when you press CTRL+R, the history search mode is activated, and `Run program:` is replaced with `Search: ` + the characters you type

That feature was broken until  gmrun-1.0w (or a bit later perhaps), it has exponentially increased my productivity.... in the console, something I never used before fixing my gmrun fork

**Comment by mazes-80** [comment]
Le Thu, 03 Mar 2022 11:54:19 -0800,
wdlkmpx ***@***.***> a écrit :

> Do you also want to remove the label widget that contains the text?
> 'Cause that's not possible
> 
> gmrun supports a bash-like search, when you press CTRL+R, the history
> search mode is activated, and `Run program:` is replaced with
> `Search: ` + the characters you type
So my suggestion to replace with just "Run :" may be ok, it shortens
things without breaking info.

> 
> That feature was broken until  gmrun-1.0w (or a bit later perhaps),
> it has exponentially increased my productivity.... in the console,
> something I never used before fixing my gmrun fork
idk when it was fixed your side when I tested 1.1w it was ok.
It was already fixed in my fork too.
You realize you missed something under bash/shell when you begin to use
it.


one feature I learnt recently under shell are sequences:
escape dot: takes last arg from last line, you can reiterate
to grab from higher in the stack
escape hash: comment out the current line, it stacks it to history
better than losing via ctrl-c
Those two increased my shell productivity a lot, the sad part: I just
noticed them about 2 years ago, what a shame.

**Comment by gen2brain** [comment]
I think just removing `program` is ok, `Run:/Search:` is enough.
Btw. I use this app for many years and it is really nice to see it maintained, and super nice that it is in C now, thanks!

**Comment by GreenLunar** [comment]
> gmrun supports a bash-like search, when you press CTRL+R, the history search mode is activated, and `Run program:` is replaced with `Search: ` + the characters you type

I didn't know that option.

> I think just removing `program` is ok, `Run:/Search:` is enough. Btw. I use this app for many years and it is really nice to see it maintained, and super nice that it is in C now, thanks!

I agree.

**Comment by wdlkmpx** [comment]
gmrun has hidden power that really takes time to understand, i.e: learn how CRTL+R works in BASH

what I think it needs is an alternate dialog app (probably not as powerful, i.e. gmexec), that includes 'Run as root' and other possible options visible in the GUI

The problem with C is that it lacks a powerful standard library like the C++ STL, with something like that the knowledge is universal and applies to all projects. glib2 is really not the solution for C and is controlled by an evil organization, and that causes me a lot of distress when I want to use something powerful and "standard" in CLI apps for example

**Comment by GreenLunar** [comment]
Who controls C?

I've never have this any thought, even though I've concluded that if I program in golang, it'll never be a software that will be able to connect to the web or any connection at all, due to the nature of its maker per se

**Comment by wdlkmpx** [comment]
The ISO C committee perhaps. 

In C, custom implementations of the same string functions linked lists and so on are very common, I see the same stuff in many projects, something that really needs to be standardized one way or another. 

A similar approach I see in old and relegated GTK apps, it's like a layer above makes sense. A toolkit above the toolkit

I guess that's why I started to write wlib2 to eventually use it in CLI projects, just like my wconf stuff that will replace auto tools in all the projects I forkjed, it's something that probably requires a psychiatrist

**Comment by GreenLunar** [comment]
It's terrible how this world/society/system (whever is the term) is engineered.

It's complex to an extent that the average person wouldn't understand or wouldn't be available to try to understand how control structures work and how they are and to what ramifications and what worst of implications it can bring with it.

Thank you for the heads up.
